import type { Metadata } from "next";
import { SITE } from "@/lib/site";

// Generated by app/opengraph-image.tsx. Overriding openGraph below drops the
// inherited file-based image, so it has to be referenced explicitly.
const shareImage = { url: "/opengraph-image", width: 1200, height: 630, alt: `${SITE.name} · ${SITE.shortTitle}` };

// /login is the only public, indexable page, so it doubles as the landing
// page for search: canonical URL, full share metadata and structured data.
export const metadata: Metadata = {
  title: "Sign in · Inventory, Sales & Shop Management",
  description: SITE.description,
  alternates: { canonical: "/login" },
  // Nested objects replace the root layout's rather than merging, so repeat
  // every field here.
  openGraph: {
    type: "website",
    siteName: SITE.name,
    title: SITE.title,
    description: SITE.description,
    url: "/login",
    locale: SITE.locale,
    images: [shareImage],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.title,
    description: SITE.description,
    images: [shareImage],
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE.url}/#organization`,
      name: SITE.name,
      url: SITE.url,
      logo: `${SITE.url}${SITE.logo}`,
    },
    {
      "@type": "WebSite",
      "@id": `${SITE.url}/#website`,
      name: SITE.name,
      url: SITE.url,
      publisher: { "@id": `${SITE.url}/#organization` },
      inLanguage: "en",
    },
    {
      "@type": "SoftwareApplication",
      name: SITE.name,
      url: `${SITE.url}/login`,
      description: SITE.description,
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web, Android, iOS, Windows, macOS",
      publisher: { "@id": `${SITE.url}/#organization` },
      featureList: [
        "Inventory and stock management",
        "Sales recording",
        "Purchases and supplier management",
        "Expense tracking",
        "Customer debt tracking",
        "Proforma invoices",
        "Real-time business reports",
      ],
    },
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="auth-page">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\u003c") }}
      />
      {children}
    </div>
  );
}
